import { Injectable } from "@angular/core";
import { HttpClient } from "@angular/common/http";

@Injectable()
export class HoldingService {
  getData() {
    return [
      {
        holdingName: '"iShares S&P/TSX Cdn Prefr Shr ETF Comm',
        holdingCode: '"',
        holdingType: "CPD",
        assetClass: "ETF",
        subAssetClass: "Fixed Income",
        sourceOfInvestment: "Fixed Income Canada",
        isLocked: "Individual",
        geography: "FALSE",
        price: "Canada",
        marketValue: "23.89",
        portfolioPercent: "7781.95",
        assetClassPercent: "23.5",
        portfolioManger: "19.3",
        clientId: "Julia Wilson",
        clientName: "23890989",
        accountId: "Barack Obama",
        accountName: "78907890",
        accountType: "Barack Obama",
        programType: "RRSP",
        estimatedAnnualDistribution: "PIM",
        currentYield: "23.8",
      },
      {
        holdingName: "PIMCO Monthly Income F",
        holdingCode: "PMO205",
        holdingType: "Mutual Fund",
        assetClass: "Fixed Income",
        subAssetClass: "Fixed Income Canada",
        sourceOfInvestment: "SMA Model: Forstrong Core Growth",
        isLocked: "TRUE",
        geography: "Canada",
        price: "2.4",
        marketValue: "225.89",
        portfolioPercent: "11.9",
        assetClassPercent: "18.9",
        portfolioManger: "Blaze Titus",
        clientId: "23890988",
        clientName: "Michelle Obama",
        accountId: "78907891",
        accountName: "Michelle Obama",
        accountType: "TFSA",
        programType: "Commission",
        estimatedAnnualDistribution: "22.9",
        currentYield: "2.4",
      },
      {
        holdingName: "Vanguard S&P 500 ETF",
        holdingCode: "VFV",
        holdingType: "ETF",
        assetClass: "Equity",
        subAssetClass: "Equity US",
        sourceOfInvestment: "SMA Model: Forstrong Core Growth",
        isLocked: "TRUE",
        geography: "US",
        price: "44.88",
        marketValue: "33900",
        portfolioPercent: "21",
        assetClassPercent: "15",
        portfolioManger: "Daniel GoodWill",
        clientId: "23890978",
        clientName: "Michelle Obama",
        accountId: "78907891",
        accountName: "Michelle Obama",
        accountType: "TFSA",
        programType: "Commission",
        estimatedAnnualDistribution: "18.1",
        currentYield: "2.2",
      },
      {
        holdingName: "Bank of Montreal",
        holdingCode: "BMO",
        holdingType: "Stock",
        assetClass: "Equity",
        subAssetClass: "Equity Canada",
        sourceOfInvestment: "PAG Model: Focus List",
        isLocked: "TRUE",
        geography: "Canada",
        price: "88.99",
        marketValue: "45678",
        portfolioPercent: "12.1",
        assetClassPercent: "14.2",
        portfolioManger: "Julia Wilson",
        clientId: "23890968",
        clientName: "Michelle Obama",
        accountId: "78907891",
        accountName: "Michelle Obama",
        accountType: "TFSA",
        programType: "Commission",
        estimatedAnnualDistribution: "15.9",
        currentYield: "2.4",
      },
      {
        holdingName: "Canadian National Railway Co",
        holdingCode: "CNR",
        holdingType: "Stock",
        assetClass: "Equity",
        subAssetClass: "Equity Canada",
        sourceOfInvestment: "PAG Model: Focus List",
        isLocked: "TRUE",
        geography: "Canada",
        price: "99.485",
        marketValue: "58737",
        portfolioPercent: "10.85",
        assetClassPercent: "12.05",
        portfolioManger: "Blaze Titus",
        clientId: "23890958",
        clientName: "Barack Obama",
        accountId: "78907891",
        accountName: "Michelle Obama",
        accountType: "TFSA",
        programType: "Commission",
        estimatedAnnualDistribution: "13.05",
        currentYield: "3.75",
      },
      {
        holdingName: "Bank of Nova Scotia",
        holdingCode: "BNS",
        holdingType: "Stock",
        assetClass: "Equity",
        subAssetClass: "Equity Canada",
        sourceOfInvestment: "PAG Model: Focus List",
        isLocked: "TRUE",
        geography: "Canada",
        price: "123.263",
        marketValue: "73475",
        portfolioPercent: "8.34",
        assetClassPercent: "10.13",
        portfolioManger: "Daniel GoodWill",
        clientId: "23890948",
        clientName: "Barack Obama",
        accountId: "78907890",
        accountName: "Barack Obama",
        accountType: "RRSP",
        programType: "PIM",
        estimatedAnnualDistribution: "10.2",
        currentYield: "2.43",
      },
      {
        holdingName: "Royal Bank of Canada",
        holdingCode: "RY",
        holdingType: "Stock",
        assetClass: "Equity",
        subAssetClass: "Equity Canada",
        sourceOfInvestment: "PAG Model: Focus List",
        isLocked: "TRUE",
        geography: "Canada",
        price: "147.041",
        marketValue: "88200",
        portfolioPercent: "5.83",
        assetClassPercent: "4.21",
        portfolioManger: "Julia Wilson",
        clientId: "23890948",
        clientName: "Barack Obama",
        accountId: "78907890",
        accountName: "Barack Obama",
        accountType: "RRSP",
        programType: "PIM",
        estimatedAnnualDistribution: "6.895",
        currentYield: "3.119",
      },
      {
        holdingName: "EdgePoint Global Portfolio Series F",
        holdingCode: "EDG500",
        holdingType: "Mutual Fund",
        assetClass: "Equity",
        subAssetClass: "Equity Global",
        sourceOfInvestment: "Individual",
        isLocked: "FALSE",
        geography: "Canada",
        price: "170.819",
        marketValue: "102945",
        portfolioPercent: "3.32",
        assetClassPercent: "6.29",
        portfolioManger: "Blaze Titus",
        clientId: "23890948",
        clientName: "Barack Obama",
        accountId: "78907890",
        accountName: "Barack Obama",
        accountType: "RRSP",
        programType: "PIM",
        estimatedAnnualDistribution: "3.85",
        currentYield: "3.28",
      },
    ];
  }

  constructor(private http: HttpClient) {}

  getHoldingData() {
    return Promise.resolve(this.getData());
  }
}
