import { Injectable } from "@angular/core";
import { HttpClient } from "@angular/common/http";

@Injectable()
export class HoldingService {
  getData() {
    return [
      {
        holdingName: "iShares S&P/TSX Cdn Prefr Shr ETF Comm",
        holdingCode: "CPD",
        holdingType: "ETF",
        assetClass: "Fixed Income",
        subAssetClass: "Fixed Income Canada",
        sourceOfInvestment: "Individual",
        isLocked: "FALSE",
        geography: "Canada",
        estimatedAnnualDistribution: 23.8,
        currentYield: 3.5,
        quantity: 25,
        price: 23.89,
        marketValue: 7781.95,
        portfolioPercent: 23.5,
        portfolioManger: "Julia Wilson",
        accounts: [
          {
            clientId: "23890989",
            clientName: "Barack Obama",
            accountId: "78907890",
            accountName: "Barack Obama",
            accountType: "RRSP",
            programType: "PIM",
            quantity: 10,
            allocation: 2000,
          },
          {
            clientId: "23890988",
            clientName: "Michelle Obama",
            accountId: "78907891",
            accountName: "Michelle Obama",
            accountType: "TFSA",
            programType: "Commission",
            quantity: 15,
            allocation: 4000,
          },
        ],
      },
      {
        holdingName: "PIMCO Monthly Income F",
        holdingCode: "PMO205",
        holdingType: "Mutual Fund",
        assetClass: "Fixed Income",
        subAssetClass: "Fixed Income Canada",
        sourceOfInvestment: "SMA Model: Forstrong Core Growth",
        isLocked: "TRUE",
        geography: "Canada",
        estimatedAnnualDistribution: 22.9,
        currentYield: 2.4,
        quantity: 20,
        price: 2.4,
        marketValue: 225.89,
        portfolioPercent: 11.9,
        portfolioManger: "Blaze Titus",
        accounts: [
          {
            clientId: "23890978",
            clientName: "Michelle Obama",
            accountId: "78907891",
            accountName: "Michelle Obama",
            accountType: "TFSA",
            programType: "Commission",
            quantity: 20,
            allocation: 2000,
          },
        ],
      },
      {
        holdingName: "Vanguard S&P 500 ETF",
        holdingCode: "VFV",
        holdingType: "ETF",
        assetClass: "Equity",
        subAssetClass: "Equity US",
        sourceOfInvestment: "SMA Model: Forstrong Core Growth",
        isLocked: "TRUE",
        geography: "US",
        estimatedAnnualDistribution: 18.1,
        currentYield: 2.2,
        quantity: 45,
        price: 44.88,
        marketValue: 33900,
        portfolioPercent: 21,
        portfolioManger: "Daniel GoodWill",
        accounts: [
          {
            clientId: "23890958",
            clientName: "Barack Obama",
            accountId: "78907891",
            accountName: "Michelle Obama",
            accountType: "TFSA",
            programType: "Commission",
            quantity: 10,
            allocation: 560000,
          },
          {
            clientId: "23890948",
            clientName: "Barack Obama",
            accountId: "78907890",
            accountName: "Barack Obama",
            accountType: "RRSP",
            programType: "PIM",
            quantity: 30,
            allocation: 889000,
          },
        ],
      },
      {
        holdingName: "Bank of Montreal",
        holdingCode: "BMO",
        holdingType: "Stock",
        assetClass: "Equity",
        subAssetClass: "Equity Canada",
        sourceOfInvestment: "PAG Model: Focus List",
        isLocked: "TRUE",
        geography: "Canada",
        estimatedAnnualDistribution: 15.9,
        currentYield: 2.4,
        quantity: 10,
        price: 88.99,
        marketValue: 45678,
        portfolioPercent: 12.1,
        portfolioManger: "Julia Wilson",
        accounts: [
          {
            clientId: "23890958",
            clientName: "Barack Obama",
            accountId: "78907891",
            accountName: "Michelle Obama",
            accountType: "TFSA",
            programType: "Commission",
            quantity: 10,
            allocation: 560000,
          },
        ],
      },
      {
        holdingName: "Canadian National Railway Co",
        holdingCode: "CNR",
        holdingType: "Stock",
        assetClass: "Equity",
        subAssetClass: "Equity Canada",
        sourceOfInvestment: "PAG Model: Focus List",
        isLocked: "TRUE",
        geography: "Canada",
        estimatedAnnualDistribution: 13.05,
        currentYield: 3.75,
        quantity: 40,
        price: 99.485,
        marketValue: 58737,
        portfolioPercent: 10.85,
        portfolioManger: "Blaze Titus",
        accounts: [
          {
            clientId: "23890989",
            clientName: "Barack Obama",
            accountId: "78907890",
            accountName: "Barack Obama",
            accountType: "RRSP",
            programType: "PIM",
            quantity: 10,
            allocation: 2000,
          },
          {
            clientId: "23890988",
            clientName: "Michelle Obama",
            accountId: "78907891",
            accountName: "Michelle Obama",
            accountType: "TFSA",
            programType: "Commission",
            quantity: 15,
            allocation: 4000,
          },
          {
            clientId: "23890978",
            clientName: "Michelle Obama",
            accountId: "78907891",
            accountName: "Michelle Obama",
            accountType: "TFSA",
            programType: "Commission",
            quantity: 20,
            allocation: 2000,
          },
        ],
      },
      {
        holdingName: "Bank of Nova Scotia",
        holdingCode: "BNS",
        holdingType: "Stock",
        assetClass: "Equity",
        subAssetClass: "Equity Canada",
        sourceOfInvestment: "PAG Model: Focus List",
        isLocked: "TRUE",
        geography: "Canada",
        estimatedAnnualDistribution: 10.2,
        currentYield: 2.43,
        quantity: 45,
        price: 123.263,
        marketValue: 73475,
        portfolioPercent: 8.34,
        portfolioManger: "Daniel GoodWill",
        accounts: [
          {
            clientId: "23890948",
            clientName: "Barack Obama",
            accountId: "78907890",
            accountName: "Barack Obama",
            accountType: "RRSP",
            programType: "PIM",
            quantity: 15,
            allocation: 111090,
          },
          {
            clientId: "23890948",
            clientName: "Barack Obama",
            accountId: "78907890",
            accountName: "Barack Obama",
            accountType: "RRSP",
            programType: "PIM",
            quantity: 20,
            allocation: 3330000,
          },
        ],
      },
      {
        holdingName: "Royal Bank of Canada",
        holdingCode: "RY",
        holdingType: "Stock",
        assetClass: "Equity",
        subAssetClass: "Equity Canada",
        sourceOfInvestment: "PAG Model: Focus List",
        isLocked: "TRUE",
        geography: "Canada",
        estimatedAnnualDistribution: 6.895,
        currentYield: 3.119,
        quantity: 20,
        price: 147.41,
        marketValue: 88200,
        portfolioPercent: 5.83,
        portfolioManger: "Julia Wilson",
        accounts: [
          {
            clientId: "23890948",
            clientName: "Barack Obama",
            accountId: "78907890",
            accountName: "Barack Obama",
            accountType: "RRSP",
            programType: "PIM",
            quantity: 15,
            allocation: 111090,
          },
          {
            clientId: "23890948",
            clientName: "Barack Obama",
            accountId: "78907890",
            accountName: "Barack Obama",
            accountType: "RRSP",
            programType: "PIM",
            quantity: 20,
            allocation: 3330000,
          },
        ],
      },
      {
        holdingName: "EdgePoint Global Portfolio Series F",
        holdingCode: "EDG500",
        holdingType: "Mutual Fund",
        assetClass: "Equity",
        subAssetClass: "Equity Global",
        sourceOfInvestment: "Individual",
        isLocked: "FALSE",
        geography: "Canada",
        estimatedAnnualDistribution: 3.85,
        currentYield: 3.28,
        quantity: 50,
        price: 170.819,
        marketValue: 102945,
        portfolioPercent: 3.32,
        portfolioManger: "Blaze Titus",
        accounts: [
          {
            clientId: "23890948",
            clientName: "Barack Obama",
            accountId: "78907890",
            accountName: "Barack Obama",
            accountType: "RRSP",
            programType: "PIM",
            quantity: 12,
            allocation: 889000,
          },
          {
            clientId: "23890948",
            clientName: "Barack Obama",
            accountId: "78907890",
            accountName: "Barack Obama",
            accountType: "RRSP",
            programType: "PIM",
            quantity: 15,
            allocation: 111090,
          },
        ],
      },
    ];
  }

  constructor(private http: HttpClient) {}

  getHoldingData() {
    return Promise.resolve(this.getData());
  }
}
